name: Mahima Katakwar
on:   
  push:
    branches: [dev]

jobs:   
  Mahima: 
    runs-on: windows-latest
    steps: 
      - name: Pune
        run: echo "hello pune"
      - name: Step 2
        run: echo "tree structure"
      - name: Step 4
        run: echo "this is step 3"
        
    
