name: Github Actions
on:
  push:
  workflow_dispatch:
jobs:   
  running_muleJobs: 
    runs-on: windows-latest
    steps: 
      - name: Running mulesoft jobs
        run: echo "Running mulesoft jobs here."
  code_checkout:
    runs-on: windows-latest
    steps:
      - name: code checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Calling Powershell Commands
        run: |
             $path = "./Files"
             $Filename = Get-ChildItem $path -File -Recurse 
             echo $Filename
             foreach ($Filename in $path) {
             #check if the file exists and has a .txt extension
             if($Filename -like ".txt") {
             #Delete the file
             Remove-Item $Filename -Recurse -Force
             Write-Host "Deleted file: $Filename" } 
             }
