name: Github Actions
on:
 push:
     branches:
      - dev
 workflow_dispatch:
jobs:   
  copy-file: 
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 2

    - name: Check git commands
      run: |
        changed_files=$(git diff HEAD^ HEAD --name-only)
        echo $changed_files
    

