name: Github Actions
on:
 push:
     branches:
      - dev
 workflow_dispatch:
jobs:   
  copy-file: 
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Check git commands
      run: |
       git log -p -1 -- "./Files/Large_Files/file1.txt"
       git --no-pager log -p -- "./Files/Large_Files/file1.txt"
      
    

