name: Four Jobs Workflow
 
on:
  schedule:
    - cron: '30 20 * * *'
 
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Job 1
        run: echo "Running Job 1"
 
  job2:
    runs-on: ubuntu-latest
    steps:
      - name: Job 2
        run: echo "Running Job 2"
 
  job3:
    runs-on: ubuntu-latest
    steps:
      - name: Job 3
        run: echo "Running Job 3"
 
  job4:
    runs-on: ubuntu-latest
    steps:
      - name: Job 4
        run: echo "Running Job 4"
