name: Github Actions
on:
 push:
     branches:
      - main
 workflow_dispatch:
jobs:   
  copy-file: 
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Check git commands
      run: git diff --name-only HEAD HEAD~1 ""
    

