name: automation_schedule
      
on:
 workflow_dispatch:

 schedule:
    - cron: '14 20 * * 4'

    
jobs:
  test_schedule:
    runs-on: ubuntu-latest
    steps:
      - name: Job one is running 
        run: echo "Job one is running"

      - name: Job two is running 
        if: github.event.schedule == '14 20 * * 4'
        run: echo "Job two is running"


        
